# Alembic script.py template for autogenerate
"""add_protocol_data_jsonb

Revision ID: 21efa9e174bb
Revises: 35ccb446bd1f
Create Date: 2026-05-21 09:47:16.814610
"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa



revision: str = '21efa9e174bb'
down_revision: Union[str, None] = '35ccb446bd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###