# Alembic script.py template for autogenerate
"""add_contracts_people_org_fields

Revision ID: 35ccb446bd1f
Revises: 656a3c5ba51a
Create Date: 2026-05-21 08:58:57.135020
"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa



revision: str = '35ccb446bd1f'
down_revision: Union[str, None] = '656a3c5ba51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###